# Generated by Django 4.2.1 on 2023-06-05 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sede', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'academic_units',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'db_table': 'academic_years',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.academicyear')),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('academic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.academicunit')),
            ],
            options={
                'db_table': 'careers',
            },
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'postulations',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TutorshipInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=25)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.area')),
            ],
            options={
                'db_table': 'tutorship_instances',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('ucc_key', models.PositiveIntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.academicyear')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='User_X_Tutorship_Instance_X_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.role')),
                ('tutorship_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.tutorshipinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.user')),
            ],
            options={
                'db_table': 'Users_X_Tutorship_Instances_X_Roles',
                'unique_together': {('user',), ('tutorship_instance',)},
            },
        ),
        migrations.CreateModel(
            name='User_X_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.user')),
            ],
            options={
                'db_table': 'Users_X_Roles',
            },
        ),
        migrations.CreateModel(
            name='User_X_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.user')),
            ],
            options={
                'db_table': 'Users_X_Areas',
            },
        ),
        migrations.CreateModel(
            name='TutorUserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=10)),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('tutor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_schedule', to='turnero.user')),
            ],
            options={
                'db_table': 'tutor_user_schedules',
            },
        ),
        migrations.CreateModel(
            name='TutorUserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('occurred', models.BooleanField()),
                ('absent', models.BooleanField()),
                ('utility', models.PositiveSmallIntegerField()),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_reviews_made', to='turnero.user')),
                ('tutor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_reviews_received', to='turnero.user')),
                ('tutorship_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.tutorshipinstance')),
            ],
            options={
                'db_table': 'tutor_user_reviews',
            },
        ),
        migrations.CreateModel(
            name='TutorshipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=50)),
                ('tutor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.user')),
                ('tutorship_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.tutorshipinstance')),
            ],
            options={
                'db_table': 'tutorship_reports',
            },
        ),
        migrations.AddField(
            model_name='tutorshipinstance',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.tutoruserschedule'),
        ),
        migrations.AddField(
            model_name='tutorshipinstance',
            name='users',
            field=models.ManyToManyField(through='turnero.User_X_Tutorship_Instance_X_Role', to='turnero.user'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(through='turnero.User_X_Role', to='turnero.user'),
        ),
        migrations.CreateModel(
            name='Postulation_X_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.area')),
                ('postulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.postulation')),
            ],
            options={
                'db_table': 'Postulations_X_Areas',
            },
        ),
        migrations.AddField(
            model_name='postulation',
            name='coordinator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_postulation_assigned', to='turnero.user'),
        ),
        migrations.AddField(
            model_name='postulation',
            name='student_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_postulation_made', to='turnero.user'),
        ),
        migrations.CreateModel(
            name='Career_X_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.user')),
            ],
            options={
                'db_table': 'Career_X_Users',
            },
        ),
        migrations.CreateModel(
            name='Career_X_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.area')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.career')),
            ],
            options={
                'db_table': 'Careers_X_Areas',
            },
        ),
        migrations.AddField(
            model_name='career',
            name='areas',
            field=models.ManyToManyField(through='turnero.Career_X_Area', to='turnero.area'),
        ),
        migrations.AddField(
            model_name='career',
            name='users',
            field=models.ManyToManyField(through='turnero.Career_X_User', to='turnero.user'),
        ),
        migrations.AddField(
            model_name='area',
            name='postulations',
            field=models.ManyToManyField(through='turnero.Postulation_X_Area', to='turnero.postulation'),
        ),
        migrations.AddField(
            model_name='area',
            name='users',
            field=models.ManyToManyField(through='turnero.User_X_Area', to='turnero.user'),
        ),
    ]
