# Generated by Django 4.2.1 on 2023-06-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0003_alter_user_ucc_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='ucc_key',
            field=models.PositiveIntegerField(),
        ),
    ]
