# Generated by Django 4.2.1 on 2023-06-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0004_rename_mail_user_email_alter_user_ucc_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ucc_key',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
