# Generated by Django 4.2.1 on 2023-06-25 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0005_alter_user_email_alter_user_ucc_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message="Only email addresses with '@ucc.edu.ar' domain are allowed.", regex='^\\d{7}@ucc.edu.ar$')]),
        ),
    ]
